# This file was generated by GoReleaser. DO NOT EDIT.
cask "hardpointd" do
  version "1.1.10"

  on_macos do
    on_intel do
      url "https://github.com/hardpointlabs/agent/releases/download/v#{version}/hardpointd_Darwin_x86_64.tar.gz"
      sha256 "890443961f1ad76cb0d14012e06ed1dc38364dcfb9e26889670a270b3a4c8339"
    end
    on_arm do
      url "https://github.com/hardpointlabs/agent/releases/download/v#{version}/hardpointd_Darwin_arm64.tar.gz"
      sha256 "abf1414fd928c1ff1d207c9cda18b1cd4c0d8f943d2059ea2a78ecf1ce4d20db"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hardpointlabs/agent/releases/download/v#{version}/hardpointd_Linux_x86_64.tar.gz"
      sha256 "8f0b239403ed86c83ccc4819c7e468a00e0aa2d483c183d391d2d3dd43e0e931"
    end
    on_arm do
      url "https://github.com/hardpointlabs/agent/releases/download/v#{version}/hardpointd_Linux_arm64.tar.gz"
      sha256 "f8e33e8a78a446075d1b79fb0b0a9084bfb7562bcce78243949bb59595b05594"
    end
  end

  name "hardpointd"
  desc "Hardpoint agent"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hardpointd"

  postflight do
    bin.install "hardpointd"
    system "#{bin}/hardpointd --version"
  end

  # No zap stanza required

end
