# This file was generated by GoReleaser. DO NOT EDIT.
cask "hardpointd" do
  version "1.1.25"

  on_macos do
    on_intel do
      url "https://github.com/hardpointlabs/agent/releases/download/v#{version}/hardpointd_Darwin_x86_64.tar.gz"
      sha256 "887f6d413b23443ee060a02906cb890f98b51541f99f4d1e408f0ca4ea2d83a9"
    end
    on_arm do
      url "https://github.com/hardpointlabs/agent/releases/download/v#{version}/hardpointd_Darwin_arm64.tar.gz"
      sha256 "302f472c61e478e8622d8ee85cf190b5ed3ec642eaf37e471ad7514f9621547a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hardpointlabs/agent/releases/download/v#{version}/hardpointd_Linux_x86_64.tar.gz"
      sha256 "478c4bf8b929b0d95cf90f79dd545a9a9f8db8857d9088b58a2cb849cb73cd4b"
    end
    on_arm do
      url "https://github.com/hardpointlabs/agent/releases/download/v#{version}/hardpointd_Linux_arm64.tar.gz"
      sha256 "10f003ae51681a69bbcf5bd1fbbb73fdcfddb40b1cbb1334608be212256c23ec"
    end
  end

  name "hardpointd"
  desc "Hardpoint agent"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hardpointd"

  postflight do
    bin.install "hardpointd"
    system "#{bin}/hardpointd --version"
  end

  # No zap stanza required

end
