# This file was generated by GoReleaser. DO NOT EDIT.
cask "hardpointd" do
  version "1.1.28"

  on_macos do
    on_intel do
      url "https://github.com/hardpointlabs/agent/releases/download/v#{version}/hardpointd_Darwin_x86_64.tar.gz"
      sha256 "a3a300425b2a8856cf6caf6894de491c367861c3913f9dfc214c4c9ed4fa2129"
    end
    on_arm do
      url "https://github.com/hardpointlabs/agent/releases/download/v#{version}/hardpointd_Darwin_arm64.tar.gz"
      sha256 "6f66bbee575f7c49d78555ddcd2fe7be7a9482a37bcef1bcb92041d0900ff30d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hardpointlabs/agent/releases/download/v#{version}/hardpointd_Linux_x86_64.tar.gz"
      sha256 "9c7e75c60012542b5ebe3e35b67dc7c5b2fd292aabcce941144cc369a08fb590"
    end
    on_arm do
      url "https://github.com/hardpointlabs/agent/releases/download/v#{version}/hardpointd_Linux_arm64.tar.gz"
      sha256 "79ad9da18657b3a3c405451209e45f21da62c4cfd9d4e3ecc58b6c1ea75b024f"
    end
  end

  name "hardpointd"
  desc "Hardpoint agent"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hardpointd"

  # No zap stanza required

end
