# This file was generated by GoReleaser. DO NOT EDIT.
cask "invar" do
  version "1.0.24"

  on_macos do
    on_arm do
      sha256 "99707ee0b60fce90f88ad92ed0bee1248785bb94ed52554a5a706c46f6d703d0"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "05ab005d6b6abdcf9a1789d15308b33a92aeec6397c9024b6c8f12f82274849b"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "97140ac5ae742b1cc8780efa0e2d499fb90120185dc54f5805242858d7ace96d"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Linux_x86_64.tar.gz"
    end
  end

  name "invar"
  desc "Hardpoint agent"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "invar"

  # No zap stanza required
end
