# This file was generated by GoReleaser. DO NOT EDIT.
cask "invar" do
  version "1.0.22"

  on_macos do
    on_arm do
      sha256 "5a85727a498d985c5d4de4a2a4d72430208a2343b012ce4ca8983c9a7c569248"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "45ddab82c6eed3690957b28fcccee7e47b3a37aceae51d83d6ece0005aa506cd"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4c6cddda694e06e3423dc08dd458a57321e4c49ae072dcf3aa1aa60c5e331dd1"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Linux_x86_64.tar.gz"
    end
  end

  name "invar"
  desc "Hardpoint agent"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "invar"

  # No zap stanza required
end
