# This file was generated by GoReleaser. DO NOT EDIT.
cask "invar" do
  version "1.0.25"

  on_macos do
    on_arm do
      sha256 "9ae1286c5549d685514fbc9deec803934a23e00a910074ba4dad53f59db9e7fb"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cb080f1ba8667f06c1ca10292ca0b3f026c6a69d076bd44e0a0e241d7b7eebcd"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "29ab593d033632f340f4e6ad42f8ff122ae910975e53023344821b55b5262758"
      url "https://github.com/hardpointlabs/invar/releases/download/v#{version}/invar_Linux_x86_64.tar.gz"
    end
  end

  name "invar"
  desc "Hardpoint agent"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "invar"

  # No zap stanza required
end
