# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HardpointAgent < Formula
  desc "Hardpoint agent"
  homepage ""
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hardpointlabs/agent/releases/download/v1.1.0/hardpoint-agent_Darwin_x86_64.tar.gz"
      sha256 "c6451d27a9a6aa007d1955648928c91c7e22c8c92cacd115c923adae7db71b57"

      define_method(:install) do
        bin.install "hardpoint-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hardpointlabs/agent/releases/download/v1.1.0/hardpoint-agent_Darwin_arm64.tar.gz"
      sha256 "fee022f786b84154d03574a4523853592ed92fb65ac37327a90945130f582ae5"

      define_method(:install) do
        bin.install "hardpoint-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hardpointlabs/agent/releases/download/v1.1.0/hardpoint-agent_Linux_x86_64.tar.gz"
      sha256 "6747302b9242b149b194be5aa690db9bd8bdd35ccb3e59159575951a86cf167d"
      define_method(:install) do
        bin.install "hardpoint-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hardpointlabs/agent/releases/download/v1.1.0/hardpoint-agent_Linux_arm64.tar.gz"
      sha256 "e0341433771655a9ce0cbd76eb5438e6ecc261aea8e857e1f55429fa61df594b"
      define_method(:install) do
        bin.install "hardpoint-agent"
      end
    end
  end

  test do
    system "#{bin}/hardpoint-agent --version"
  end
end
